### ISSUE TITLE
Add `download` option

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rustc_codegen_gcc#398]
Using this option, it would download the latest version of `libgccjit.so` built in CI. To do we would need to replace the existing `gcc_path` with an actual config file which would contain:

```toml
download-libgccjit = true|false
libgccjit-path = "path"
```

If `download-libgccjit` is `true`, then `libgccjit-path` will be ignored.
